name: Build, Test, and Deploy
run-name: ${{ github.actor }}


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master  ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install modules
        run: npm ci
#        working-directory: ./apps/frontend/

      - name: Build frontend
        run: npm run dev
#        working-directory: ./apps/frontend/
#
      - name: Run tests
        run: npm run test:unit
#        working-directory: ./apps/frontend/