name: Build, Test, and Deploy

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm i
        working-directory: ./apps/frontend/

      - name: Build frontend
        run: npm run dev
        working-directory: ./apps/frontend/

      - name: Run tests
        run: npm run test:unit
        working-directory: ./apps/frontend/