name: Build, Test, and Deploy

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Install modules
        run: npm i
        working-directory: ./apps/frontend/

      - name: Build frontend
        run: npm run dev
        working-directory: ./apps/frontend/

      - name: Run tests
        run: npm run test:unit
        working-directory: ./apps/frontend/