name: Build, Test, and Deploy
run-name: ${{ github.actor }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main  ]

jobs:
  pinepline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm ci
        working-directory: ./apps/frontend/


      - name: Run tests
        run: npm run test:unit
        working-directory: ./apps/frontend/