name: Testing P
run-name: ${{ github.actor }}
on:
  push:
    branches:
      [ master ]
    pull_request:
      branches: [ master ]
jobs:
  pinepline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

  steps:
    - uses: actions/checkout@v4
    - name: Staring Node.js ${{ matrix.node-version }}
      uses: actions/step-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: cd frontend
      run: cd .\apps\frontend\
    - name: install modules
      run: npm i
    - name: build pp
      run: npm run dev
